#include "GameConsole.h"
bool testAllTests();
bool horizontalBounceTest();
bool collideBallTest();
bool updateBallTest();
bool updatePaddleTest();
bool pingUpdateFSMTest();
bool updatePlayerTest();
bool checkCollisionTest();
bool checkBulletCollisionsTest();
bool spawnBulletTest();
bool updateBulletsTest();
bool switchToPingTest();
bool switchToDodgeTest();
bool updateFSMTest();
bool DodgeUpdateFSMTest();
bool resetISRTest();
bool homeISRTest();
bool processReponseTest();